version: '3.8'

services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      - .mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080

volumes:
  mysql_data:
